services:
  db:
    image: postgres:17.6
    container_name: shelftiro-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shelftiro-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
